### ISSUE TITLE
data type

### ISSUE THREAD

**Issue by ketanjadh** [9von10/ngx-cytoscapejs#15]
can you please provide in which format i have to pass data

**Comment by 9von10** [comment]
Hey ketanjadh,

you can provide the data either via the `[cytoscapeOptions]` or the `[cxData]` input. The `[cytoScapeOptions]` input accepts a [Cytoscape.js graph model](https://js.cytoscape.org/#notation/graph-model) and the `[cxData]` input needs a [Cytoscape Exhange Data Model](https://home.ndexbio.org/data-model/).

For an usage example please have a look at the demo project found in the [projects/demo-app](https://github.com/9von10/ngx-cytoscapejs/tree/main/projects/demo-app/src/app) folder. Some example models can be found in the [projects/demo-app/src/assets](https://github.com/9von10/ngx-cytoscapejs/tree/main/projects/demo-app/src/assets) folder as JSON files.

Let me know if that helps you.
