### ISSUE TITLE
Version 1.7.0 deployed on NPM refer to Angular 16 instead of Angular 17

### ISSUE THREAD

**Issue by hostettler** [9von10/ngx-cytoscapejs#18]
Version 1.7.0 deployed on NPM refer to Angular 16 instead of Angular 17 despite the tag in Github being correct.

**Comment by 9von10** [comment]
Hello,

thanks for the hint and the PR. I have just published version 1.7.1 on NPM, which fixes the bug.
I have also updated both Angular and Cytoscape to the latest version.

Best regards

**Comment by hostettler** [comment]
Thanks for the quick turnaround.
