### ISSUE TITLE
Access to attributeNameMap

### ISSUE THREAD

**Issue by SherlockMones** [9von10/ngx-cytoscapejs#9]
Hello kind sir,

## Problem

I am using your library when rendering CX networks. The node and edge properties can be read from the core without any problems. I am however having issues with [cytoscape.js selectors](https://js.cytoscape.org/#selectors/data), since the CX converter changes their property names (they append `_u1`, `_u2` etc to distinguish properties I guess). 

## Steps to reproduce

The changes in network property names can be validated via this tool: https://frankkramer-lab.github.io/NDExEdit.

- Load this sample network via UUID: 5820d988-68d5-11e7-961c-0ac135e8bacf
- Select some nodes in the network
- Check the table of selected nodes for the property names

The respective section in the converter: https://github.com/cytoscape/cx2js/blob/master/src/cx_to_js.js#L418

## Favored solution

As far as I know, the correct property names, that can be used to make selections on the core, are stored in the `attributeNameMap`, the CX converter uses during conversion. If you could extend the library to add another `Output()` containing this `attributeNameMap`, that would be awesome.

## Project

- Angular 13.3.4
- Node: 16.15.0
- NgRx 13.1.0
- ngx-cytoscapejs 1.0.0

**Comment by 9von10** [comment]
Hello SherlockMones,

thanks again for another issue 😄. I've added the requested output.
Please check out the just released version 1.1.0 on npm.

**Comment by SherlockMones** [comment]
That was fast, thanks! Works perfectly.
